### ISSUE TITLE
.NET Core

### ISSUE THREAD

**Issue by stanislavromanov** [shawnmclean/SimpleCrypto.net#10]
Can you make this package available for .NET Core? Currently it's giving error. I've made my own implementation meanwhile.

> Package SimpleCrypto 0.3.30.26 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). 
> Package SimpleCrypto 0.3.30.26 supports: net (.NETFramework,Version=v0.0)
> One or more packages are incompatible with .NETCoreApp,Version=v1.0.

Here is what I use meanwhile: https://www.nuget.org/packages/SimpleCrypto.NetCore
Source: https://gitlab.com/stanislavromanov/SimpleCrypto.NetCore

**Comment by martinjt** [comment]
Why don't you do a pull request? I'd like to see this too.

**Comment by stanislavromanov** [comment]
I don't know how to convert this to .net core. I know only how to create new .net core package

**Comment by geersch** [comment]
Old thread, but it might help somebody in the future. Came across this package when porting some old code to .NET core. 

It's not that much work to rewrite it.

First you need to install the `Microsoft.AspNetCore.Cryptography.KeyDerivation` package.

To hash a password:

```
string hashed = Convert.ToBase64String(KeyDerivation.Pbkdf2(
  password: password,
  salt: Encoding.UTF8.GetBytes(salt),
  prf: KeyDerivationPrf.HMACSHA1,
  iterationCount: iterationCount,
  numBytesRequested: 64
));
```

To compare it against a stored hashed password.

```
var equal = string.Compare(hashedPassword1, hashedPassword2) == 0;
```

You can also port the compare function from this library and use that instead.

And finally if you want to generate a salt.

```
byte[] salt = new byte[128 / 8];
using (var rng = RandomNumberGenerator.Create())
{
  rng.GetBytes(salt);
}
var base64salt = Convert.ToBase64String(salt);
```

**Comment by stanislavromanov** [comment]
Apparently I already did rewrite it 4 years ago (https://www.nuget.org/packages/SimpleCrypto.NetCore). From my comment it seemed that I did not know how to convert this existing project to .NET Core package so instead I just created a new one!

Could you do a PR then?
